#!/usr/bin/env python3

import sys

user = ""
shame = ""



if len(sys.argv) != 2 or len(sys.argv) != 3:
    print("USAGE: gitbuildcheck <--shame> <username/program>"

    exit(1)

if len(sys.argv) == 2:
    user = sys.argv(1)

if len(sys.argv) == 3:
    user = sys.argv(2)
    shame = sys.argv(1)
    
